// Purchase Orders — Phase 3 of the materials management system.
//
// A PO is one supplier's slice of one or more material lists' "need"
// lines. Generated by `generateDraftsFromMaterialList(list, parts,
// suppliers)` which groups need lines by their primary supplier (the
// first entry in part.supplierIds[]) and emits one draft per supplier.
// Each draft snapshots prices from parts.json at generation time so
// the PDF and total don't drift if the catalog updates later.
//
// ID format: PO-YYYY-NNNN. Per-year counter, mirrors the rest.
//
// Status enum:
//   draft               — created from a material list, not yet sent
//   sent                — emailed to supplier; source material-list lines
//                         flipped to "ordered" with poId backref. Locked
//                         from edits.
//   partially_received  — some lines fully received, others outstanding
//                         (Phase 4 partial-receive support)
//   received            — every line fully received; source material-list
//                         lines flipped from "ordered" to "have"
//   cancelled           — terminal; outstanding source lines flipped back
//                         to "need" (poId cleared) so they can be re-ordered
//
// State-flip mechanics (the dance with material-lists.js):
//   draft -> sent             — flip each sourceLine to status="ordered" + poId=this.id
//   sent  -> partially_recv   — flip fully-received sourceLines to "have"; partial stay "ordered"
//   any   -> received         — flip remaining "ordered" sourceLines to "have"
//   any   -> cancelled        — flip outstanding "ordered" sourceLines back to "need" + poId=null
//                               (already-received lines stay "have" — can't undo a delivery)
//
// Each PO line carries `receivedQty` (default 0). A line is "fully
// received" when receivedQty >= qty. `deriveStatus()` walks the lines
// and flips the PO status atomically with each receipt event.
//
// Storage: server/data/purchase-orders.json. Same flat-file pattern;
// rotate to SQLite at ~10k.

const fs = require("node:fs/promises");
const fsSync = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const FILE = path.join(__dirname, "..", "data", "purchase-orders.json");

const STATUSES = ["draft", "sent", "partially_received", "received", "cancelled"];

// ---- File I/O ---------------------------------------------------------

async function ensureFile() {
  await fs.mkdir(path.dirname(FILE), { recursive: true });
  if (!fsSync.existsSync(FILE)) {
    await fs.writeFile(FILE, "[]\n", "utf8");
  }
}

async function readAll() {
  await ensureFile();
  try {
    const raw = await fs.readFile(FILE, "utf8");
    const parsed = JSON.parse(raw || "[]");
    return Array.isArray(parsed) ? parsed.map(hydrate) : [];
  } catch {
    return [];
  }
}

async function writeAll(records) {
  await ensureFile();
  await fs.writeFile(FILE, JSON.stringify(records, null, 2) + "\n", "utf8");
}

// ---- Helpers ---------------------------------------------------------

function nowIso() { return new Date().toISOString(); }

function makePoLineId() {
  return "poli_" + crypto.randomBytes(6).toString("base64url");
}

function hydrateLine(line) {
  const sku = typeof line?.sku === "string" ? line.sku.trim() : "";
  const qty = Number(line?.qty);
  const safeQty = Number.isFinite(qty) && qty > 0 ? Math.floor(qty) : 1;
  const unitCents = Number.isFinite(Number(line?.unitPriceCents)) ? Math.max(0, Math.floor(Number(line.unitPriceCents))) : 0;
  // receivedQty defaults to 0 and is bounded [0, qty]. Storing it on the
  // line lets a single PO go through partial receipts: receive 8 today,
  // receive the remaining 4 next week. Status derivation reads it.
  const rawReceived = Number(line?.receivedQty);
  const receivedQty = Number.isFinite(rawReceived) && rawReceived > 0 ? Math.min(safeQty, Math.floor(rawReceived)) : 0;
  return {
    id: typeof line?.id === "string" && line.id ? line.id : makePoLineId(),
    sku,
    qty: safeQty,
    sourceListId: typeof line?.sourceListId === "string" ? line.sourceListId : null,
    sourceLineId: typeof line?.sourceLineId === "string" ? line.sourceLineId : null,
    unitPriceCents: unitCents,
    lineTotalCents: unitCents * safeQty,
    notes: typeof line?.notes === "string" ? line.notes.slice(0, 500) : "",
    receivedQty,
    receivedAt: typeof line?.receivedAt === "string" ? line.receivedAt : null
  };
}

// Walk PO lines and decide whether the PO is sent / partially_received /
// received. Used after every receipt event to keep the PO status in sync
// with the line states. Returns the new status; doesn't mutate.
function deriveReceiveStatus(lineItems) {
  const lines = Array.isArray(lineItems) ? lineItems : [];
  if (!lines.length) return "draft";
  let anyReceived = false;
  let allFullyReceived = true;
  for (const l of lines) {
    const recv = Number(l.receivedQty) || 0;
    const ord = Number(l.qty) || 0;
    if (recv > 0) anyReceived = true;
    if (recv < ord) allFullyReceived = false;
  }
  if (allFullyReceived) return "received";
  if (anyReceived) return "partially_received";
  return "sent";
}

function blankPo() {
  const created = nowIso();
  return {
    id: "",
    status: "draft",

    supplierId: null,
    // Snapshots of supplier fields at create time. The PDF + email use
    // these so a supplier rename doesn't retroactively change a sent PO.
    supplierName: "",
    supplierEmail: "",
    supplierContactName: "",
    supplierPhone: "",
    supplierAddress: "",

    // Source material-list ids. Usually one; supports many for the case
    // where the admin merges several lists into one PO.
    sourceMaterialListIds: [],

    lineItems: [],
    subtotalCents: 0,

    notes: "",                  // free-form notes; printed on the PDF
    internalNotes: "",          // never on the PDF — admin-only

    // Email send state. Snapshotted at send time so we can show "sent
    // to orders@vendor.com on Mar 14" without re-fetching the supplier.
    emailedToEmail: "",
    emailedToName: "",
    emailSubject: "",

    sentAt: null,
    receivedAt: null,
    cancelledAt: null,
    cancelReason: "",

    createdAt: created,
    updatedAt: created,
    createdBy: "admin",

    history: [
      { ts: created, action: "created", by: "admin", note: "" }
    ]
  };
}

function hydrate(rec) {
  const base = blankPo();
  return {
    ...base,
    ...rec,
    status: STATUSES.includes(rec?.status) ? rec.status : "draft",
    sourceMaterialListIds: Array.isArray(rec?.sourceMaterialListIds) ? rec.sourceMaterialListIds.slice() : [],
    lineItems: Array.isArray(rec?.lineItems) ? rec.lineItems.map(hydrateLine) : [],
    history: Array.isArray(rec?.history) ? rec.history.slice(-200) : []
  };
}

async function nextPoId(year) {
  const records = await readAll();
  const prefix = `PO-${year}-`;
  let max = 0;
  for (const r of records) {
    if (typeof r.id === "string" && r.id.startsWith(prefix)) {
      const n = parseInt(r.id.slice(prefix.length), 10);
      if (Number.isFinite(n) && n > max) max = n;
    }
  }
  return `${prefix}${String(max + 1).padStart(4, "0")}`;
}

function appendHistory(record, entry) {
  record.history = Array.isArray(record.history) ? record.history : [];
  record.history.push({ ts: nowIso(), by: "admin", note: "", ...entry });
  if (record.history.length > 200) record.history = record.history.slice(-200);
}

function recomputeSubtotal(record) {
  let sub = 0;
  for (const l of record.lineItems || []) sub += Number(l.lineTotalCents) || 0;
  record.subtotalCents = sub;
}

// ---- CRUD -----------------------------------------------------------

async function list({ status = null, supplierId = null, materialListId = null } = {}) {
  const records = await readAll();
  return records.filter((r) => {
    if (status && r.status !== status) return false;
    if (supplierId && r.supplierId !== supplierId) return false;
    if (materialListId && !(r.sourceMaterialListIds || []).includes(materialListId)) return false;
    return true;
  });
}

async function get(id) {
  const records = await readAll();
  return records.find((r) => r.id === id) || null;
}

async function create({
  supplierId = null,
  supplierName = "",
  supplierEmail = "",
  supplierContactName = "",
  supplierPhone = "",
  supplierAddress = "",
  sourceMaterialListIds = [],
  lineItems = [],
  notes = "",
  internalNotes = "",
  createdBy = "admin"
} = {}) {
  const records = await readAll();
  const year = new Date().getUTCFullYear();
  const id = await nextPoId(year);
  const rec = blankPo();
  rec.id = id;
  rec.supplierId = supplierId ? String(supplierId) : null;
  rec.supplierName = String(supplierName || "").trim().slice(0, 200);
  rec.supplierEmail = String(supplierEmail || "").trim().toLowerCase().slice(0, 254);
  rec.supplierContactName = String(supplierContactName || "").trim().slice(0, 120);
  rec.supplierPhone = String(supplierPhone || "").trim().slice(0, 40);
  rec.supplierAddress = String(supplierAddress || "").trim().slice(0, 400);
  rec.sourceMaterialListIds = Array.isArray(sourceMaterialListIds) ? sourceMaterialListIds.filter(Boolean).map(String) : [];
  rec.lineItems = Array.isArray(lineItems) ? lineItems.map(hydrateLine) : [];
  rec.notes = String(notes || "").slice(0, 4000);
  rec.internalNotes = String(internalNotes || "").slice(0, 4000);
  rec.createdBy = String(createdBy || "admin").slice(0, 80);
  recomputeSubtotal(rec);
  records.unshift(rec);
  await writeAll(records);
  return rec;
}

// Update editable fields. Status changes ALWAYS go through the dedicated
// markSent / markReceived / markCancelled functions so the source-line
// state flips happen atomically with the PO state.
async function update(id, patch = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const current = records[idx];
  if (current.status !== "draft" && (Array.isArray(patch.lineItems) || patch.supplierId !== undefined)) {
    throw new Error(`Cannot edit line items or supplier on a ${current.status} PO`);
  }
  const next = { ...current };
  const allowedTop = ["notes", "internalNotes", "supplierName", "supplierEmail", "supplierContactName", "supplierPhone", "supplierAddress"];
  for (const key of allowedTop) {
    if (Object.prototype.hasOwnProperty.call(patch, key)) {
      if (key === "supplierEmail") {
        next.supplierEmail = String(patch.supplierEmail || "").trim().toLowerCase().slice(0, 254);
      } else {
        next[key] = String(patch[key] == null ? "" : patch[key]).slice(0, 4000);
      }
    }
  }
  if (patch.supplierId !== undefined) {
    next.supplierId = patch.supplierId ? String(patch.supplierId) : null;
  }
  if (Array.isArray(patch.lineItems)) {
    next.lineItems = patch.lineItems.map(hydrateLine);
    recomputeSubtotal(next);
  }
  next.updatedAt = nowIso();
  records[idx] = next;
  await writeAll(records);
  return next;
}

// Mark a draft as sent. Records the email send-state snapshot. Caller
// (server.js) is responsible for: actually rendering the PDF, calling
// the email sender, and flipping the source material-list lines to
// "ordered" with poId backref.
async function markSent(id, { toEmail, toName, subject } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status !== "draft") {
    throw new Error(`Can only send a draft PO. This one is "${rec.status}".`);
  }
  if (!rec.lineItems.length) throw new Error("Can't send a PO with no line items.");
  rec.status = "sent";
  rec.sentAt = nowIso();
  rec.emailedToEmail = String(toEmail || rec.supplierEmail || "").trim().toLowerCase();
  rec.emailedToName = String(toName || rec.supplierContactName || rec.supplierName || "");
  rec.emailSubject = String(subject || `Purchase Order ${rec.id}`).slice(0, 200);
  rec.updatedAt = rec.sentAt;
  appendHistory(rec, { action: "sent", note: rec.emailedToEmail });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

// Record a receipt event. `lineUpdates` is a `{ [lineId]: newReceivedQty }`
// map of ABSOLUTE quantities (not deltas). Pass an empty object (or omit
// it) to mark every line fully received at once. Each line's receivedQty
// is clamped to [0, line.qty]. PO status is auto-derived from the line
// states after the update.
//
// Returns:
//   {
//     po: <updated record>,
//     fullyReceivedLineIds: [...] // lines that crossed into receivedQty >= qty
//                                 // on THIS event (caller flips source lines)
//   }
//
// The caller (server.js /receive endpoint) flips source material-list
// lines to "have" only for the IDs in fullyReceivedLineIds — partial
// lines stay "ordered" with poId backref so a subsequent receive event
// can complete them.
async function markReceived(id, { lineUpdates = null, note = "" } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status !== "sent" && rec.status !== "partially_received") {
    throw new Error(`Can only receive a sent or partially-received PO. This one is "${rec.status}".`);
  }
  const ts = nowIso();
  const fullyReceivedLineIds = [];

  // Resolve the requested per-line qtys. If the caller didn't pass any,
  // treat as "mark every line fully received."
  const updatesMap = (lineUpdates && typeof lineUpdates === "object" && !Array.isArray(lineUpdates))
    ? lineUpdates
    : null;

  for (const line of rec.lineItems) {
    const wasFullyReceived = (Number(line.receivedQty) || 0) >= (Number(line.qty) || 0);
    let newReceived;
    if (updatesMap) {
      // Only touch lines explicitly in the updates map. Absent lines keep
      // their current receivedQty.
      if (!Object.prototype.hasOwnProperty.call(updatesMap, line.id)) continue;
      const requested = Number(updatesMap[line.id]);
      newReceived = Number.isFinite(requested) && requested >= 0
        ? Math.min(Math.floor(requested), line.qty)
        : line.receivedQty;
    } else {
      newReceived = line.qty;
    }
    if (newReceived === line.receivedQty) continue;
    line.receivedQty = newReceived;
    line.receivedAt = ts;
    if (!wasFullyReceived && newReceived >= line.qty) {
      fullyReceivedLineIds.push(line.id);
    }
  }

  // Derive new PO status from line states.
  const newStatus = deriveReceiveStatus(rec.lineItems);
  const statusChanged = newStatus !== rec.status;
  rec.status = newStatus;
  if (newStatus === "received" && !rec.receivedAt) rec.receivedAt = ts;
  rec.updatedAt = ts;

  // Concise history entry — "received 8 of 12 lines" or "partial: 3 lines"
  const totalLines = rec.lineItems.length;
  const fullyDoneCount = rec.lineItems.filter((l) => (l.receivedQty || 0) >= l.qty).length;
  appendHistory(rec, {
    action: statusChanged ? `status:${newStatus}` : "receipt_recorded",
    note: note ? `${fullyDoneCount}/${totalLines} lines fully received — ${note}` : `${fullyDoneCount}/${totalLines} lines fully received`
  });

  records[idx] = rec;
  await writeAll(records);
  return { po: rec, fullyReceivedLineIds };
}

// Cancel a PO. Allowed from draft / sent / partially_received. Already-
// received lines stay "have" on their source lists (can't undo a delivery
// — the supplier already shipped). Outstanding (not fully received) lines
// flip back to "need" — those line ids are returned so server.js can do
// the source-list flip.
//
// Returns:
//   {
//     po: <cancelled record>,
//     outstandingLineIds: [...]   // lines that were NOT fully received,
//                                  // caller flips their source lines back
//                                  // to "need" and clears poId
//   }
async function markCancelled(id, { reason = "" } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status === "received") {
    throw new Error("Can't cancel a fully-received PO. Mark a return separately.");
  }
  if (rec.status === "cancelled") return { po: rec, outstandingLineIds: [] }; // idempotent
  const outstandingLineIds = [];
  for (const line of rec.lineItems) {
    if ((Number(line.receivedQty) || 0) < (Number(line.qty) || 0)) {
      outstandingLineIds.push(line.id);
    }
  }
  rec.status = "cancelled";
  rec.cancelledAt = nowIso();
  rec.cancelReason = String(reason || "").slice(0, 500);
  rec.updatedAt = rec.cancelledAt;
  appendHistory(rec, { action: "cancelled", note: rec.cancelReason });
  records[idx] = rec;
  await writeAll(records);
  return { po: rec, outstandingLineIds };
}

async function remove(id) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const [removed] = records.splice(idx, 1);
  await writeAll(records);
  return removed;
}

// ---- Generation from a material list -------------------------------
//
// Group a material list's "need" lines by their primary supplier (the
// first entry in part.supplierIds[]). Returns:
//   {
//     ok: bool,
//     drafts: [{ supplierId, lineItems, subtotalCents }],
//     missingSupplier: [sku],   // need-line SKUs with no supplier assignment
//     missingSupplierLines: [{ sku, qty, lineId }]
//   }
//
// Caller: if drafts is non-empty, persist each via create() and gather
// the resulting PO ids. Use the missingSupplier list to surface a
// blocker UI ("3 SKUs need supplier assignment before generating").
//
// Pricing: snapshotted from `parts[sku].priceCents` at generation time.
function planDraftsFromMaterialList(list, parts) {
  if (!list || !Array.isArray(list.lineItems)) {
    return { ok: false, drafts: [], missingSupplier: [], missingSupplierLines: [] };
  }
  const drafts = new Map();   // supplierId -> { supplierId, lineItems[] }
  const missingSupplier = new Set();
  const missingSupplierLines = [];
  for (const line of list.lineItems) {
    if (line.status !== "need") continue;
    const part = parts && parts[line.sku];
    const supplierIds = (part && Array.isArray(part.supplierIds)) ? part.supplierIds : [];
    if (!supplierIds.length) {
      missingSupplier.add(line.sku);
      missingSupplierLines.push({ sku: line.sku, qty: line.qty, lineId: line.id });
      continue;
    }
    const primary = supplierIds[0];
    if (!drafts.has(primary)) {
      drafts.set(primary, { supplierId: primary, lineItems: [], subtotalCents: 0 });
    }
    const draft = drafts.get(primary);
    const unitCents = part && Number.isFinite(Number(part.priceCents)) ? Math.max(0, Math.floor(Number(part.priceCents))) : 0;
    const qty = Math.max(1, Math.floor(Number(line.qty) || 1));
    draft.lineItems.push({
      sku: line.sku,
      qty,
      sourceListId: list.id,
      sourceLineId: line.id,
      unitPriceCents: unitCents,
      lineTotalCents: unitCents * qty,
      notes: line.notes || ""
    });
    draft.subtotalCents += unitCents * qty;
  }
  return {
    ok: drafts.size > 0 && missingSupplier.size === 0,
    drafts: Array.from(drafts.values()),
    missingSupplier: Array.from(missingSupplier),
    missingSupplierLines
  };
}

// Clone a PO into a new draft (Phase 4 "re-order" feature). Same supplier,
// same line items at the same quantities, prices snapshotted at clone
// time from parts.json (passed in by caller — same shape as
// planDraftsFromMaterialList). Drops sourceMaterialListIds — re-orders
// aren't tied to a list. Returns the freshly-created PO.
//
// `note` is optional; defaults to a back-reference like "Re-order from
// PO-2026-0001" so the audit trail makes the lineage obvious.
async function reorderFrom(sourcePoId, parts) {
  const source = await get(sourcePoId);
  if (!source) throw new Error(`Source PO ${sourcePoId} not found`);
  // Snapshot line items, refreshing prices from the catalog at re-order
  // time. If a SKU has been removed from the catalog (rare), keep the
  // original price so the new draft stays usable.
  const lineItems = source.lineItems.map((line) => {
    const part = parts && parts[line.sku];
    const unitCents = part && Number.isFinite(Number(part.priceCents))
      ? Math.max(0, Math.floor(Number(part.priceCents)))
      : line.unitPriceCents;
    return {
      sku: line.sku,
      qty: line.qty,
      // No source list back-ref on a re-order — it's a fresh procurement
      // event independent of any material list.
      sourceListId: null,
      sourceLineId: null,
      unitPriceCents: unitCents,
      lineTotalCents: unitCents * line.qty,
      notes: line.notes || ""
    };
  });
  const newPo = await create({
    supplierId: source.supplierId,
    supplierName: source.supplierName,
    supplierEmail: source.supplierEmail,
    supplierContactName: source.supplierContactName,
    supplierPhone: source.supplierPhone,
    supplierAddress: source.supplierAddress,
    sourceMaterialListIds: [],
    lineItems,
    notes: source.notes ? `Re-order of ${source.id}. ${source.notes}` : `Re-order of ${source.id}.`,
    internalNotes: source.internalNotes || ""
  });
  // Add a history entry on the NEW PO that points back at the source.
  const all = await readAll();
  const idx = all.findIndex((r) => r.id === newPo.id);
  if (idx !== -1) {
    appendHistory(all[idx], { action: "reorder_of", note: source.id });
    await writeAll(all);
    return all[idx];
  }
  return newPo;
}

// Mark a re-send event on a sent / partially-received PO. Doesn't change
// status — just records that the PDF was re-emailed and snapshots the
// recipient if it changed. Caller is responsible for actually sending
// the email + rendering the PDF.
async function markResent(id, { toEmail, toName, subject } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status !== "sent" && rec.status !== "partially_received") {
    throw new Error(`Can only re-send a sent or partially-received PO. This one is "${rec.status}".`);
  }
  const ts = nowIso();
  if (toEmail) rec.emailedToEmail = String(toEmail).trim().toLowerCase();
  if (toName) rec.emailedToName = String(toName);
  if (subject) rec.emailSubject = String(subject).slice(0, 200);
  rec.updatedAt = ts;
  appendHistory(rec, { action: "resent", note: rec.emailedToEmail });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

module.exports = {
  STATUSES,
  list,
  get,
  create,
  update,
  markSent,
  markReceived,
  markCancelled,
  markResent,
  reorderFrom,
  remove,
  planDraftsFromMaterialList,
  deriveReceiveStatus
};
