// Purchase Orders — Phase 3 of the materials management system.
//
// A PO is one supplier's slice of one or more material lists' "need"
// lines. Generated by `generateDraftsFromMaterialList(list, parts,
// suppliers)` which groups need lines by their primary supplier (the
// first entry in part.supplierIds[]) and emits one draft per supplier.
// Each draft snapshots prices from parts.json at generation time so
// the PDF and total don't drift if the catalog updates later.
//
// ID format: PO-YYYY-NNNN. Per-year counter, mirrors the rest.
//
// Status enum:
//   draft               — created from a material list, not yet sent
//   sent                — emailed to supplier; source material-list lines
//                         flipped to "ordered" with poId backref. Locked
//                         from edits.
//   partially_received  — some lines fully received, others outstanding
//                         (Phase 4 partial-receive support)
//   received            — every line fully received; source material-list
//                         lines flipped from "ordered" to "have"
//   cancelled           — terminal; outstanding source lines flipped back
//                         to "need" (poId cleared) so they can be re-ordered
//
// State-flip mechanics (the dance with material-lists.js):
//   draft -> sent             — flip each sourceLine to status="ordered" + poId=this.id
//   sent  -> partially_recv   — flip fully-received sourceLines to "have"; partial stay "ordered"
//   any   -> received         — flip remaining "ordered" sourceLines to "have"
//   any   -> cancelled        — flip outstanding "ordered" sourceLines back to "need" + poId=null
//                               (already-received lines stay "have" — can't undo a delivery)
//
// Each PO line carries `receivedQty` (default 0). A line is "fully
// received" when receivedQty >= qty. `deriveStatus()` walks the lines
// and flips the PO status atomically with each receipt event.
//
// Storage: server/data/purchase-orders.json. Same flat-file pattern;
// rotate to SQLite at ~10k.

const fs = require("node:fs/promises");
const fsSync = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { resolveLineDescription } = require("./format");
const { withPurchasingLock, atomicWrite, PurchasingError, assertNotHeld, holdFor, addHolds } = require("./purchasing-store");

// The records a PO touches: itself and every material list it links to.
// A recovery hold on any of them blocks writing it (purchasing-store.js).
function poRefs(rec) {
  return {
    purchaseOrders: [rec && rec.id].filter(Boolean),
    materialLists: [...(rec && rec.sourceMaterialListIds || []), ...((rec && rec.lineItems) || []).map((l) => l && l.sourceListId)].filter(Boolean)
  };
}

const FILE = path.join(__dirname, "..", "data", "purchase-orders.json");

const STATUSES = ["draft", "sent", "partially_received", "received", "cancelled"];

// ---- File I/O ---------------------------------------------------------

async function ensureFile() {
  await fs.mkdir(path.dirname(FILE), { recursive: true });
  if (!fsSync.existsSync(FILE)) {
    await fs.writeFile(FILE, "[]\n", "utf8");
  }
}

async function readAll() {
  await ensureFile();
  try {
    const raw = await fs.readFile(FILE, "utf8");
    const parsed = JSON.parse(raw || "[]");
    return Array.isArray(parsed) ? parsed.map(hydrate) : [];
  } catch {
    return [];
  }
}

function serialize(records) {
  return JSON.stringify(records, null, 2) + "\n";
}

// Temp file + rename: a crash mid-write can never leave half a file.
async function writeAll(records) {
  await ensureFile();
  await atomicWrite(FILE, serialize(records));
}

// The file exactly as stored — no hydrate, and a parse failure THROWS
// rather than reading as empty, so a purchasing commit can never write
// back an empty list over records it failed to read. purchasing.js
// replaces only the record it changes; every other one goes back
// byte-for-byte.
async function readRaw() {
  await ensureFile();
  const parsed = JSON.parse((await fs.readFile(FILE, "utf8")) || "[]");
  if (!Array.isArray(parsed)) throw new Error("purchase-orders.json is not a list");
  return parsed;
}

// ---- Helpers ---------------------------------------------------------

function nowIso() { return new Date().toISOString(); }

function makePoLineId() {
  return "poli_" + crypto.randomBytes(6).toString("base64url");
}

function hydrateLine(line) {
  const sku = typeof line?.sku === "string" ? line.sku.trim() : "";
  const qty = Number(line?.qty);
  const safeQty = Number.isFinite(qty) && qty > 0 ? Math.floor(qty) : 1;
  const unitCents = Number.isFinite(Number(line?.unitPriceCents)) ? Math.max(0, Math.floor(Number(line.unitPriceCents))) : 0;
  // receivedQty defaults to 0 and is bounded [0, qty]. Storing it on the
  // line lets a single PO go through partial receipts: receive 8 today,
  // receive the remaining 4 next week. Status derivation reads it.
  const rawReceived = Number(line?.receivedQty);
  const receivedQty = Number.isFinite(rawReceived) && rawReceived > 0 ? Math.min(safeQty, Math.floor(rawReceived)) : 0;
  return {
    id: typeof line?.id === "string" && line.id ? line.id : makePoLineId(),
    sku,
    qty: safeQty,
    sourceListId: typeof line?.sourceListId === "string" ? line.sourceListId : null,
    sourceLineId: typeof line?.sourceLineId === "string" ? line.sourceLineId : null,
    // Description typed on a manual / off-catalog line. Snapshotted here
    // so the PDF/CSV/detail renderers can show the entered text instead of
    // re-deriving from parts.json (which falls back to "(SKU …)" when the
    // SKU isn't catalogued). Blank for catalogue-driven lines, which still
    // resolve their description from the catalog at render time. 240-char
    // cap matches parts.js's description limit.
    description: typeof line?.description === "string" ? line.description.trim().slice(0, 240) : "",
    unitPriceCents: unitCents,
    lineTotalCents: unitCents * safeQty,
    notes: typeof line?.notes === "string" ? line.notes.slice(0, 500) : "",
    receivedQty,
    receivedAt: typeof line?.receivedAt === "string" ? line.receivedAt : null,
    // The office's review of a line whose material list or list line no
    // longer exists (2026-10-03) — set ONLY by releasing that PO's
    // recovery hold (purchasing.js releaseRecoveryHold); stripped from
    // anything a browser sends (fromClient, below).
    ...(line && line.sourceMissingAcknowledged && typeof line.sourceMissingAcknowledged === "object"
      ? { sourceMissingAcknowledged: {
          at: String(line.sourceMissingAcknowledged.at || ""), by: String(line.sourceMissingAcknowledged.by || ""),
          note: String(line.sourceMissingAcknowledged.note || "").slice(0, 500) } }
      : {})
  };
}

// A line as typed or sent by a browser: never carries the office's
// missing-source acknowledgment.
function fromClient(line) {
  if (!line || typeof line !== "object") return hydrateLine(line);
  const { sourceMissingAcknowledged, ...rest } = line;
  return hydrateLine(rest);
}

// The lines of this PO whose material list, or line on it, no longer
// exists (2026-10-03) and that the office hasn't yet reviewed. `lists` —
// every material list, archived and trashed included.
function missingSources(po, lists) {
  const out = [];
  for (const l of (po && po.lineItems) || []) {
    if (!l || !l.sourceListId || !l.sourceLineId || l.sourceMissingAcknowledged) continue;
    const list = (lists || []).find((x) => x && x.id === l.sourceListId);
    if (!list) out.push({ sku: l.sku, listId: l.sourceListId, lineId: l.sourceLineId, what: `list ${l.sourceListId}` });
    else if (!(list.lineItems || []).some((x) => x && x.id === l.sourceLineId)) {
      out.push({ sku: l.sku, listId: l.sourceListId, lineId: l.sourceLineId, what: `line ${l.sourceLineId} of list ${l.sourceListId}` });
    }
  }
  return out;
}

// A sent, received or cancelled PO whose source is gone is historical
// purchasing evidence the system can't place on a job: it is locked
// (a recovery hold, released only by the office with a note) before any
// further send, receive, cancel, re-send or re-order. A draft is left to
// the send gate, which refuses it (purchasing.js assertLinesOrderable).
function assertSourcesPresent(po, lists) {
  if (!po || (po.status || "draft") === "draft") return;
  const missing = missingSources(po, lists);
  if (!missing.length) return;
  addHolds([{
    scope: "purchase_order", id: po.id, source: "source_missing",
    reason: `${po.id} (${po.status}) is for ${missing.map((m) => `${m.sku} — ${m.what}`).join("; ")}, which no longer exist${missing.length === 1 ? "s" : ""}`
  }]);
  assertNotHeld({ purchaseOrders: [po.id] });
}

// Every check a lifecycle action on this PO makes before it does anything
// — a recovery hold, or a source that is gone. Reads the lists itself.
async function assertActionable(po) {
  assertNotHeld(poRefs(po));
  assertSourcesPresent(po, await require("./material-lists").list({ includeArchived: true, includeDeleted: true }));
}

// Walk PO lines and decide whether the PO is sent / partially_received /
// received. Used after every receipt event to keep the PO status in sync
// with the line states. Returns the new status; doesn't mutate.
function deriveReceiveStatus(lineItems) {
  const lines = Array.isArray(lineItems) ? lineItems : [];
  if (!lines.length) return "draft";
  let anyReceived = false;
  let allFullyReceived = true;
  for (const l of lines) {
    const recv = Number(l.receivedQty) || 0;
    const ord = Number(l.qty) || 0;
    if (recv > 0) anyReceived = true;
    if (recv < ord) allFullyReceived = false;
  }
  if (allFullyReceived) return "received";
  if (anyReceived) return "partially_received";
  return "sent";
}

function blankPo() {
  const created = nowIso();
  return {
    id: "",
    status: "draft",

    supplierId: null,
    // Snapshots of supplier fields at create time. The PDF + email use
    // these so a supplier rename doesn't retroactively change a sent PO.
    supplierName: "",
    supplierEmail: "",
    supplierContactName: "",
    supplierPhone: "",
    supplierAddress: "",

    // Source material-list ids. Usually one; supports many for the case
    // where the admin merges several lists into one PO.
    sourceMaterialListIds: [],

    lineItems: [],
    subtotalCents: 0,

    notes: "",                  // free-form notes; printed on the PDF
    internalNotes: "",          // never on the PDF — admin-only

    // Email send state. Snapshotted at send time so we can show "sent
    // to orders@vendor.com on Mar 14" without re-fetching the supplier.
    emailedToEmail: "",
    emailedToName: "",
    emailSubject: "",

    sentAt: null,
    // A send that started — marked ON DISK before the supplier email goes
    // (2026-10-02), cleared in the same save that records the outcome. If
    // the server dies in between, it survives the restart and the PO is
    // "delivery uncertain": it will not be emailed again until the office
    // records whether it went (purchasing.resolveUncertainPoSend). The
    // same pattern as a change request's sendInFlight (2026-09-27).
    sendInFlight: null,       // { at, by, to }
    sendAttempts: [],         // [{ at, by, to, ok, reason, … }] — kept for good
    receivedAt: null,
    cancelledAt: null,
    cancelReason: "",

    createdAt: created,
    updatedAt: created,
    createdBy: "admin",

    history: [
      { ts: created, action: "created", by: "admin", note: "" }
    ],

    // Bulk-operations soft state. Only draft POs are eligible for soft-delete
    // (sent / received POs touch supplier orders and inventory state). Gate
    // enforced at dispatcher.
    deletedAt: null,

    // Snapshot-on-send paths (PO Document Redesign brief §3.5). When the
    // PO transitions draft → sent, the rendered PDF and the CSV companion
    // are written to disk and these fields are set. Re-sending uses the
    // stored files unchanged — byte-identical to the original send. A
    // parts.json change after send NEVER alters the documents a supplier
    // already received. Null on draft POs; immutable once sent.
    pdfPath: null,
    csvPath: null,
    documentsGeneratedAt: null
  };
}

function hydrate(rec) {
  const base = blankPo();
  return {
    ...base,
    ...rec,
    status: STATUSES.includes(rec?.status) ? rec.status : "draft",
    sourceMaterialListIds: Array.isArray(rec?.sourceMaterialListIds) ? rec.sourceMaterialListIds.slice() : [],
    lineItems: Array.isArray(rec?.lineItems) ? rec.lineItems.map(hydrateLine) : [],
    history: Array.isArray(rec?.history) ? rec.history.slice(-200) : [],
    sendInFlight: rec?.sendInFlight && typeof rec.sendInFlight === "object" ? rec.sendInFlight : null,
    sendAttempts: Array.isArray(rec?.sendAttempts) ? rec.sendAttempts : [],
    deletedAt: typeof rec?.deletedAt === "string" ? rec.deletedAt : null,
    pdfPath: typeof rec?.pdfPath === "string" ? rec.pdfPath : null,
    csvPath: typeof rec?.csvPath === "string" ? rec.csvPath : null,
    documentsGeneratedAt: typeof rec?.documentsGeneratedAt === "string" ? rec.documentsGeneratedAt : null
  };
}

async function nextPoId(year) {
  const records = await readAll();
  const prefix = `PO-${year}-`;
  let max = 0;
  for (const r of records) {
    if (typeof r.id === "string" && r.id.startsWith(prefix)) {
      const n = parseInt(r.id.slice(prefix.length), 10);
      if (Number.isFinite(n) && n > max) max = n;
    }
  }
  return `${prefix}${String(max + 1).padStart(4, "0")}`;
}

function appendHistory(record, entry) {
  record.history = Array.isArray(record.history) ? record.history : [];
  record.history.push({ ts: nowIso(), by: "admin", note: "", ...entry });
  if (record.history.length > 200) record.history = record.history.slice(-200);
}

function recomputeSubtotal(record) {
  let sub = 0;
  for (const l of record.lineItems || []) sub += Number(l.lineTotalCents) || 0;
  record.subtotalCents = sub;
}

// ---- CRUD -----------------------------------------------------------

async function list({ status = null, supplierId = null, materialListId = null, includeDeleted = false } = {}) {
  const records = await readAll();
  return records.filter((r) => {
    if (!includeDeleted && r.deletedAt) return false;
    if (status && r.status !== status) return false;
    if (supplierId && r.supplierId !== supplierId) return false;
    if (materialListId && !(r.sourceMaterialListIds || []).includes(materialListId)) return false;
    return true;
  });
}

async function get(id) {
  const records = await readAll();
  return records.find((r) => r.id === id) || null;
}

async function create({
  supplierId = null,
  supplierName = "",
  supplierEmail = "",
  supplierContactName = "",
  supplierPhone = "",
  supplierAddress = "",
  sourceMaterialListIds = [],
  lineItems = [],
  notes = "",
  internalNotes = "",
  createdBy = "admin"
} = {}, { extraHistory = [] } = {}) {
  assertNotHeld({ purchaseOrders: [], materialLists: [...(sourceMaterialListIds || []), ...(lineItems || []).map((l) => l && l.sourceListId)] });
  const records = await readAll();
  const year = new Date().getUTCFullYear();
  const id = await nextPoId(year);
  const rec = blankPo();
  rec.id = id;
  rec.supplierId = supplierId ? String(supplierId) : null;
  rec.supplierName = String(supplierName || "").trim().slice(0, 200);
  rec.supplierEmail = String(supplierEmail || "").trim().toLowerCase().slice(0, 254);
  rec.supplierContactName = String(supplierContactName || "").trim().slice(0, 120);
  rec.supplierPhone = String(supplierPhone || "").trim().slice(0, 40);
  rec.supplierAddress = String(supplierAddress || "").trim().slice(0, 400);
  rec.sourceMaterialListIds = Array.isArray(sourceMaterialListIds) ? sourceMaterialListIds.filter(Boolean).map(String) : [];
  rec.lineItems = Array.isArray(lineItems) ? lineItems.map(fromClient) : [];
  rec.notes = String(notes || "").slice(0, 4000);
  rec.internalNotes = String(internalNotes || "").slice(0, 4000);
  rec.createdBy = String(createdBy || "admin").slice(0, 80);
  recomputeSubtotal(rec);
  for (const entry of extraHistory) appendHistory(rec, entry);
  records.unshift(rec);
  await writeAll(records);
  return rec;
}

// Update editable fields. Status changes ALWAYS go through purchasing.js
// (send / receive / cancel), which moves the source material-list lines in
// the same commit as the PO.
async function update(id, patch = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const current = records[idx];
  assertNotHeld(poRefs(current));
  if (Array.isArray(patch.lineItems)) assertNotHeld({ materialLists: patch.lineItems.map((l) => l && l.sourceListId) });
  if (current.status !== "draft" && (Array.isArray(patch.lineItems) || patch.supplierId !== undefined)) {
    throw new Error(`Cannot edit line items or supplier on a ${current.status} PO`);
  }
  const next = { ...current };
  const allowedTop = ["notes", "internalNotes", "supplierName", "supplierEmail", "supplierContactName", "supplierPhone", "supplierAddress"];
  for (const key of allowedTop) {
    if (Object.prototype.hasOwnProperty.call(patch, key)) {
      if (key === "supplierEmail") {
        next.supplierEmail = String(patch.supplierEmail || "").trim().toLowerCase().slice(0, 254);
      } else {
        next[key] = String(patch[key] == null ? "" : patch[key]).slice(0, 4000);
      }
    }
  }
  if (patch.supplierId !== undefined) {
    next.supplierId = patch.supplierId ? String(patch.supplierId) : null;
  }
  if (Array.isArray(patch.lineItems)) {
    next.lineItems = patch.lineItems.map(fromClient);
    recomputeSubtotal(next);
  }
  next.updatedAt = nowIso();
  records[idx] = next;
  await writeAll(records);
  return next;
}

// ---- Lifecycle transitions ------------------------------------------
//
// Pure: each takes a hydrated PO, changes it in place, and returns what
// changed. None of them reads or writes a file — purchasing.js does that,
// in one commit with the source material-list lines, under the shared
// purchasing lock (2026-10-02). An illegal transition throws a
// PurchasingError BEFORE anything is written.

// Draft → sent. Records the email send-state snapshot AND the stored-
// document paths (PO Document Redesign brief §3.5 — snapshot-on-send).
// `pdfPath` and `csvPath` are repo-relative paths under server/data/.
// Once set on a sent PO they are IMMUTABLE — the resend path reads these
// files verbatim; the supplier always receives the same bytes.
function uncertainSendError(rec) {
  const f = rec.sendInFlight || {};
  return new PurchasingError(
    `A send of ${rec.id} to ${f.to || "the supplier"} started ${f.at || "earlier"}${f.by ? ` by ${f.by}` : ""} was interrupted before its result was saved, so we can't tell whether the email arrived. Check your sent mail or ask the supplier, then record whether it went — it will not be emailed again until you do.`,
    { status: 409, code: "delivery_uncertain" }
  );
}

function assertSendable(rec) {
  if (rec.sendInFlight) throw uncertainSendError(rec);
  if (rec.status !== "draft") {
    throw new PurchasingError(`Can only send a draft PO. This one is "${rec.status}".`, { status: 409, code: "not_draft" });
  }
  if (!rec.lineItems.length) throw new PurchasingError("Can't send a PO with no line items.", { status: 422, code: "no_lines" });
}

// `inFlight` — the send this PO was marked with before its email went;
// the outcome is saved in the same write that clears the mark.
function transitionSent(rec, { toEmail, toName, subject, pdfPath, csvPath, inFlight = null, by = "admin" } = {}) {
  if (!inFlight || !rec.sendInFlight || rec.sendInFlight.at !== inFlight.at) assertSendable(rec);
  else if (rec.status !== "draft") throw new PurchasingError(`Can only send a draft PO. This one is "${rec.status}".`, { status: 409, code: "not_draft" });
  rec.sendInFlight = null;
  rec.status = "sent";
  rec.sentAt = nowIso();
  rec.emailedToEmail = String(toEmail || rec.supplierEmail || "").trim().toLowerCase();
  rec.emailedToName = String(toName || rec.supplierContactName || rec.supplierName || "");
  rec.emailSubject = String(subject || `Purchase Order ${rec.id}`).slice(0, 200);
  rec.updatedAt = rec.sentAt;
  // The caller passes both — partial snapshots (one without the other)
  // would break the resend idempotency guarantee.
  if (pdfPath) rec.pdfPath = String(pdfPath);
  if (csvPath) rec.csvPath = String(csvPath);
  if (pdfPath || csvPath) rec.documentsGeneratedAt = rec.sentAt;
  rec.sendAttempts = [...(rec.sendAttempts || []), { at: rec.sentAt, by, to: rec.emailedToEmail, ok: true, reason: null }];
  appendHistory(rec, { action: "sent", note: rec.emailedToEmail });
  return { changed: true };
}

// A receipt event. `lineUpdates` is a `{ [lineId]: newReceivedQty }` map
// of ABSOLUTE quantities (not deltas), so the same request sent twice
// lands on the same numbers — a retry can never count a delivery twice.
// Omit it to mark every line fully received. Each line's receivedQty is
// clamped to [0, line.qty]; the PO status is derived from the lines.
//
// Asking again for what is already recorded changes nothing (no history
// entry, no write) — including "mark all received" on a received PO. A
// DIFFERENT quantity on a received PO is refused, as before.
function transitionReceived(rec, { lineUpdates = null, note = "" } = {}) {
  const updatesMap = (lineUpdates && typeof lineUpdates === "object" && !Array.isArray(lineUpdates))
    ? lineUpdates
    : null;
  const wanted = (line) => {
    if (!updatesMap) return line.qty;
    if (!Object.prototype.hasOwnProperty.call(updatesMap, line.id)) return line.receivedQty;
    const requested = Number(updatesMap[line.id]);
    return Number.isFinite(requested) && requested >= 0 ? Math.min(Math.floor(requested), line.qty) : line.receivedQty;
  };
  const changes = rec.lineItems.filter((l) => wanted(l) !== l.receivedQty);
  if (rec.status === "received" && !changes.length) return { changed: false, fullyReceivedLineIds: [] };
  if (rec.status !== "sent" && rec.status !== "partially_received") {
    throw new PurchasingError(`Can only receive a sent or partially-received PO. This one is "${rec.status}".`, { status: 400, code: "not_receivable" });
  }
  if (!changes.length) return { changed: false, fullyReceivedLineIds: [] };

  const ts = nowIso();
  const fullyReceivedLineIds = [];
  for (const line of changes) {
    const wasFullyReceived = (Number(line.receivedQty) || 0) >= (Number(line.qty) || 0);
    line.receivedQty = wanted(line);
    line.receivedAt = ts;
    if (!wasFullyReceived && line.receivedQty >= line.qty) fullyReceivedLineIds.push(line.id);
  }
  const newStatus = deriveReceiveStatus(rec.lineItems);
  const statusChanged = newStatus !== rec.status;
  rec.status = newStatus;
  if (newStatus === "received" && !rec.receivedAt) rec.receivedAt = ts;
  rec.updatedAt = ts;
  // Concise history entry — "8/12 lines fully received"
  const totalLines = rec.lineItems.length;
  const fullyDoneCount = rec.lineItems.filter((l) => (l.receivedQty || 0) >= l.qty).length;
  appendHistory(rec, {
    action: statusChanged ? `status:${newStatus}` : "receipt_recorded",
    note: note ? `${fullyDoneCount}/${totalLines} lines fully received — ${note}` : `${fullyDoneCount}/${totalLines} lines fully received`
  });
  return { changed: true, fullyReceivedLineIds };
}

// Cancel. Allowed from draft / sent / partially_received. What already
// arrived stays received (can't undo a delivery); the outstanding lines'
// source lines go back to "need" (purchasing.js). Cancelling a cancelled
// PO changes nothing.
function transitionCancelled(rec, { reason = "" } = {}) {
  if (rec.status === "received") {
    throw new PurchasingError("Can't cancel a fully-received PO. Mark a return separately.", { status: 400, code: "already_received" });
  }
  if (rec.status === "cancelled") return { changed: false, outstandingLineIds: [] };
  const outstandingLineIds = rec.lineItems
    .filter((l) => (Number(l.receivedQty) || 0) < (Number(l.qty) || 0))
    .map((l) => l.id);
  rec.status = "cancelled";
  rec.cancelledAt = nowIso();
  rec.cancelReason = String(reason || "").slice(0, 500);
  rec.updatedAt = rec.cancelledAt;
  appendHistory(rec, { action: "cancelled", note: rec.cancelReason });
  return { changed: true, outstandingLineIds };
}

async function remove(id) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  assertNotHeld(poRefs(records[idx]));
  const [removed] = records.splice(idx, 1);
  await writeAll(records);
  return removed;
}

// ---- Generation from a material list -------------------------------
//
// Group a material list's "need" lines by their primary supplier (the
// first entry in part.supplierIds[]). Returns:
//   {
//     ok: bool,
//     drafts: [{ supplierId, lineItems, subtotalCents }],
//     missingSupplier: [sku],   // need-line SKUs with no supplier assignment
//     missingSupplierLines: [{ sku, qty, lineId }]
//   }
//
// Caller: if drafts is non-empty, persist each via create() and gather
// the resulting PO ids. Use the missingSupplier list to surface a
// blocker UI ("3 SKUs need supplier assignment before generating").
//
// Pricing: snapshotted from `parts[sku].priceCents` at generation time.
//
// ONE-SUPPLIER MODE (`forceSupplierId`). Grouping by each part's assigned
// supplier splits a single shopping trip across two branches — and both
// suppliers' volume discounts are all-or-nothing, so a split order can
// cost MORE than buying everything at the dearer one. Passing
// forceSupplierId puts every need line on that supplier's single draft
// instead. Two consequences, both deliberate:
//   * a SKU with no supplier assigned is no longer a blocker — the
//     supplier was named explicitly, so there is nothing to look up;
//   * each line is priced from THAT supplier's quote when we have one
//     (part.supplierPrices[supplierId], lib/part-supplier-prices.js) and
//     falls back to the catalog price otherwise. `unpricedForSupplier`
//     names the fallbacks so the UI can say which lines are a guess.
// THE "still to order" calculation (2026-10-02) — one function, used by
// every path that proposes a quantity for a list line: PO generation
// (plan + generate, assigned or one supplier), re-order, quote-request
// planning (plan + generate), and the send gate. For each line of a list,
// across every PO that claims it:
//   received — arrived on any non-draft PO, cancelled ones included (the
//              same arithmetic as purchasing-audit's "received")
//   onOrder  — still outstanding on a sent / partially received PO
//   drafted  — on a draft PO not yet sent
// A cancelled PO that delivered part of a line leaves the line at "need"
// for the REST: what to order is the line's quantity less what arrived,
// never the whole line again.
function commitmentsByListLine(purchaseOrders, listId, { excludePoId = null } = {}) {
  const out = new Map();
  const slot = (id) => { if (!out.has(id)) out.set(id, { received: 0, onOrder: 0, drafted: 0 }); return out.get(id); };
  for (const po of purchaseOrders || []) {
    if (!po || po.deletedAt || (excludePoId && po.id === excludePoId)) continue;
    for (const l of po.lineItems || []) {
      if (!l || l.sourceListId !== listId || !l.sourceLineId) continue;
      const qty = Math.max(0, Number(l.qty) || 0);
      const got = Math.min(qty, Math.max(0, Number(l.receivedQty) || 0));
      const c = slot(l.sourceLineId);
      if (po.status === "draft") { c.drafted += qty; continue; }
      c.received += got;
      if (po.status === "sent" || po.status === "partially_received") c.onOrder += qty - got;
    }
  }
  return out;
}

// How many of a line are still to be ordered. `includeDrafts`: count a
// draft PO as already arranged — true for anything that CREATES a PO (so a
// second Generate, a double-click or a re-order can't draft the same parts
// twice); false for a quote request, which may ask about parts a draft is
// waiting on.
function stillToOrder(line, commitments, { includeDrafts = true } = {}) {
  const c = (commitments && commitments.get(line.id)) || { received: 0, onOrder: 0, drafted: 0 };
  const qty = Math.max(0, Math.floor(Number(line.qty) || 0));
  return Math.max(0, qty - c.received - c.onOrder - (includeDrafts ? c.drafted : 0));
}

// Back-compat for callers that only want what arrived.
function receivedByListLine(purchaseOrders, listId) {
  const out = new Map();
  for (const [id, c] of commitmentsByListLine(purchaseOrders, listId)) out.set(id, c.received);
  return out;
}

// `committed` — commitmentsByListLine() for this list. A "need" line orders
// only what is still to come (stillToOrder, drafts counted); one already
// covered in full is skipped. Without it, the whole line quantity.
function planDraftsFromMaterialList(list, parts, { forceSupplierId = null, committed = null } = {}) {
  if (!list || !Array.isArray(list.lineItems)) {
    return { ok: false, drafts: [], missingSupplier: [], missingSupplierLines: [], unpricedForSupplier: [] };
  }
  const forced = forceSupplierId ? String(forceSupplierId).trim() : "";
  const drafts = new Map();   // supplierId -> { supplierId, lineItems[] }
  const missingSupplier = new Set();
  const missingSupplierLines = [];
  const unpricedForSupplier = [];
  for (const line of list.lineItems) {
    if (line.status !== "need") continue;
    const toOrder = committed ? stillToOrder(line, committed) : Math.max(1, Math.floor(Number(line.qty) || 1));
    if (toOrder <= 0) continue;
    const part = parts && parts[line.sku];
    const supplierIds = (part && Array.isArray(part.supplierIds)) ? part.supplierIds : [];
    if (!forced && !supplierIds.length) {
      missingSupplier.add(line.sku);
      missingSupplierLines.push({ sku: line.sku, qty: line.qty, lineId: line.id });
      continue;
    }
    const primary = forced || supplierIds[0];
    if (!drafts.has(primary)) {
      drafts.set(primary, { supplierId: primary, lineItems: [], subtotalCents: 0 });
    }
    const draft = drafts.get(primary);
    // In one-supplier mode the line is priced from that supplier's own
    // quote where we have it; the catalog price (the PRIMARY supplier's)
    // would otherwise quote branch A's money for branch B's order.
    let sourceCents = part ? part.priceCents : null;
    if (forced) {
      const theirs = part && part.supplierPrices ? part.supplierPrices[forced] : null;
      if (theirs && Number.isFinite(Number(theirs.priceCents))) sourceCents = theirs.priceCents;
      else unpricedForSupplier.push(line.sku);
    }
    const unitCents = Number.isFinite(Number(sourceCents)) ? Math.max(0, Math.floor(Number(sourceCents))) : 0;
    const qty = toOrder;
    draft.lineItems.push({
      sku: line.sku,
      qty,
      sourceListId: list.id,
      sourceLineId: line.id,
      // Snapshot the description at generation (ML lines carry no
      // description, so this resolves to the catalog description). Storing
      // it means every later render reads the same frozen text instead of
      // re-deriving from a catalog that may differ across surfaces.
      description: resolveLineDescription(line, parts),
      unitPriceCents: unitCents,
      lineTotalCents: unitCents * qty,
      notes: line.notes || ""
    });
    draft.subtotalCents += unitCents * qty;
  }
  return {
    ok: drafts.size > 0 && missingSupplier.size === 0,
    drafts: Array.from(drafts.values()),
    missingSupplier: Array.from(missingSupplier),
    missingSupplierLines,
    unpricedForSupplier
  };
}

// Clone a PO into a new draft (Phase 4 "re-order" feature). Same supplier,
// same line items at the same quantities, prices snapshotted at clone
// time from parts.json (passed in by caller — same shape as
// planDraftsFromMaterialList). Returns the freshly-created PO.
//
// A re-order KEEPS the source PO's material-list link — the PO's
// sourceMaterialListIds and each line's sourceListId / sourceLineId
// (2026-10-02). It used to drop them ("re-orders aren't tied to a list"),
// and a job's materials are found through that link, so whatever arrived
// on a re-order counted toward no job. A PO that never had a link (made by
// hand) gives its re-order none; nothing is inferred.
//
// `note` is optional; defaults to a back-reference like "Re-order from
// PO-2026-0001" so the audit trail makes the lineage obvious.
async function reorderFrom(sourcePoId, parts) {
  const source = await get(sourcePoId);
  if (!source) throw new Error(`Source PO ${sourcePoId} not found`);
  // A re-order links to the same lists — never to one whose state is in doubt.
  assertNotHeld(poRefs(source));
  // What a re-order may claim (2026-10-02): only a list line that still
  // needs ordering — "need" and on no PO. A repeat purchase of parts the
  // list already has keeps the list and project link (sourceListId,
  // sourceMaterialListIds) but claims no line, so no list line is ever
  // "on order" twice. Read under the purchasing lock.
  const listsNow = await require("./material-lists").list({ includeArchived: true, includeDeleted: true });
  assertSourcesPresent(source, listsNow);   // a PO whose list is gone: locked until reviewed
  const lineNow = (listId, lineId) => {
    const l = listsNow.find((x) => x.id === listId);
    return l ? (l.lineItems || []).find((x) => x.id === lineId) || null : null;
  };
  // A cancelled PO is re-ordered for what didn't arrive; anything else is
  // a repeat of the whole order.
  const outstanding = (line) => source.status === "cancelled"
    ? Math.max(0, (Number(line.qty) || 0) - (Number(line.receivedQty) || 0))
    : Number(line.qty) || 0;
  // Snapshot line items, refreshing prices from the catalog at re-order
  // time. If a SKU has been removed from the catalog (rare), keep the
  // original price so the new draft stays usable.
  // A line it claims is also capped at what that list line still needs —
  // so re-ordering twice, or after a Generate already drafted the rest,
  // proposes nothing more (stillToOrder, drafts counted).
  const allPos = await readAll();
  const capFor = (line, target) => stillToOrder(target, commitmentsByListLine(allPos, line.sourceListId));
  const lineItems = source.lineItems.map((line) => {
    const target = line.sourceListId && line.sourceLineId ? lineNow(line.sourceListId, line.sourceLineId) : null;
    const claims = Boolean(target && target.status === "need" && !target.poId);
    return { line, target, claims, qty: claims ? Math.min(outstanding(line), capFor(line, target)) : outstanding(line) };
  }).filter((x) => x.qty > 0).map(({ line, claims, qty }) => {
    const part = parts && parts[line.sku];
    const unitCents = part && Number.isFinite(Number(part.priceCents))
      ? Math.max(0, Math.floor(Number(part.priceCents)))
      : line.unitPriceCents;
    return {
      sku: line.sku,
      qty,
      // The same list line it was ordered for, when that line still needs
      // ordering — so sending, receiving and cancelling the re-order move
      // it, and the job counts it.
      sourceListId: line.sourceListId || null,
      sourceLineId: claims ? line.sourceLineId : null,
      // Carry the description forward (source line's stored snapshot wins;
      // else re-resolve from the catalog at re-order time, like the price).
      description: resolveLineDescription(line, parts),
      unitPriceCents: unitCents,
      lineTotalCents: unitCents * qty,
      notes: line.notes || ""
    };
  });
  if (!lineItems.length) throw new PurchasingError(`Nothing to re-order: everything on ${source.id} arrived.`, { status: 409, code: "nothing_to_reorder" });
  const newPo = await create({
    supplierId: source.supplierId,
    supplierName: source.supplierName,
    supplierEmail: source.supplierEmail,
    supplierContactName: source.supplierContactName,
    supplierPhone: source.supplierPhone,
    supplierAddress: source.supplierAddress,
    sourceMaterialListIds: Array.isArray(source.sourceMaterialListIds) ? source.sourceMaterialListIds.slice() : [],
    lineItems,
    notes: source.notes ? `Re-order of ${source.id}. ${source.notes}` : `Re-order of ${source.id}.`,
    internalNotes: source.internalNotes || ""
  }, {
    // The back-reference is written WITH the new PO — one write, so a
    // re-order can't exist without the record of what it re-orders.
    extraHistory: [{ action: "reorder_of", note: source.id }]
  });
  return newPo;
}

// Mark a re-send event on a sent / partially-received PO. Doesn't change
// status — just records that the PDF was re-emailed and snapshots the
// recipient if it changed. Caller is responsible for actually sending
// the email + rendering the PDF.
async function markResent(id, { toEmail, toName, subject } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  await assertActionable(rec);
  if (rec.status !== "sent" && rec.status !== "partially_received") {
    throw new Error(`Can only re-send a sent or partially-received PO. This one is "${rec.status}".`);
  }
  const ts = nowIso();
  if (toEmail) rec.emailedToEmail = String(toEmail).trim().toLowerCase();
  if (toName) rec.emailedToName = String(toName);
  if (subject) rec.emailSubject = String(subject).slice(0, 200);
  rec.updatedAt = ts;
  appendHistory(rec, { action: "resent", note: rec.emailedToEmail });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

// ---- Soft-delete (bulk operations) ----------------------------------

async function softDelete(id) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) throw new Error("Purchase order not found");
  assertNotHeld(poRefs(records[idx]));
  if (records[idx].deletedAt) throw new Error("Already in Trash");
  records[idx] = { ...records[idx], deletedAt: nowIso(), updatedAt: nowIso() };
  await writeAll(records);
  return records[idx];
}

async function restore(id) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) throw new Error("Purchase order not found");
  assertNotHeld(poRefs(records[idx]));
  if (!records[idx].deletedAt) throw new Error("Not in Trash");
  records[idx] = { ...records[idx], deletedAt: null, updatedAt: nowIso() };
  await writeAll(records);
  return records[idx];
}

async function listDeleted() {
  const records = await readAll();
  return records.filter((r) => r.deletedAt);
}

async function purgeDeleted({ olderThanMs = 30 * 24 * 60 * 60 * 1000 } = {}) {
  const records = await readAll();
  const cutoff = Date.now() - olderThanMs;
  assertNotHeld({ purchaseOrders: [], materialLists: [] });   // a hold on everything stops the purge
  const kept = records.filter((r) => {
    if (!r.deletedAt) return true;
    if (holdFor(poRefs(r))) return true;                         // never purge a held record
    const t = Date.parse(r.deletedAt);
    return !Number.isFinite(t) || t > cutoff;
  });
  const purged = records.length - kept.length;
  if (purged > 0) await writeAll(kept);
  return purged;
}

// Every write verb queues behind the shared purchasing lock, so none can
// land between the two halves of a send / receive / cancel commit.
const locked = (fn) => (...args) => withPurchasingLock(() => fn(...args));

module.exports = {
  STATUSES,
  FILE,
  list,
  get,
  create: locked(create),
  update: locked(update),
  markResent: locked(markResent),
  reorderFrom: locked(reorderFrom),
  remove: locked(remove),
  planDraftsFromMaterialList,
  receivedByListLine,
  commitmentsByListLine,
  stillToOrder,
  deriveReceiveStatus,
  softDelete: locked(softDelete),
  restore: locked(restore),
  listDeleted,
  purgeDeleted: locked(purgeDeleted),
  // purchasing.js only — it holds the lock and commits the result.
  poRefs,
  missingSources,
  assertSourcesPresent,
  assertActionable,
  _internal: { readRaw, serialize, hydrate, assertSendable, uncertainSendError, appendHistory, nowIso, transitionSent, transitionReceived, transitionCancelled }
};
