// Purchase Orders — Phase 3 of the materials management system.
//
// A PO is one supplier's slice of one or more material lists' "need"
// lines. Generated by `generateDraftsFromMaterialList(list, parts,
// suppliers)` which groups need lines by their primary supplier (the
// first entry in part.supplierIds[]) and emits one draft per supplier.
// Each draft snapshots prices from parts.json at generation time so
// the PDF and total don't drift if the catalog updates later.
//
// ID format: PO-YYYY-NNNN. Per-year counter, mirrors the rest.
//
// Status enum:
//   draft      — created from a material list, not yet sent
//   sent       — emailed to supplier; source material-list lines flipped
//                to "ordered" with poId backref. Locked from edits.
//   received   — supplier delivered; source material-list lines flipped
//                from "ordered" to "have"
//   cancelled  — terminal; source material-list lines flipped back to
//                "need" (poId cleared) so they can be re-ordered
//
// State-flip mechanics (the dance with material-lists.js):
//   draft -> sent       — caller flips each sourceLine to status="ordered" + poId=this.id
//   sent  -> received   — caller flips each sourceLine to status="have"
//   any   -> cancelled  — caller flips ordered lines back to status="need" + poId=null
// (received -> anything else is blocked: once received, the PO is closed.)
//
// Storage: server/data/purchase-orders.json. Same flat-file pattern;
// rotate to SQLite at ~10k.

const fs = require("node:fs/promises");
const fsSync = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const FILE = path.join(__dirname, "..", "data", "purchase-orders.json");

const STATUSES = ["draft", "sent", "received", "cancelled"];

// ---- File I/O ---------------------------------------------------------

async function ensureFile() {
  await fs.mkdir(path.dirname(FILE), { recursive: true });
  if (!fsSync.existsSync(FILE)) {
    await fs.writeFile(FILE, "[]\n", "utf8");
  }
}

async function readAll() {
  await ensureFile();
  try {
    const raw = await fs.readFile(FILE, "utf8");
    const parsed = JSON.parse(raw || "[]");
    return Array.isArray(parsed) ? parsed.map(hydrate) : [];
  } catch {
    return [];
  }
}

async function writeAll(records) {
  await ensureFile();
  await fs.writeFile(FILE, JSON.stringify(records, null, 2) + "\n", "utf8");
}

// ---- Helpers ---------------------------------------------------------

function nowIso() { return new Date().toISOString(); }

function makePoLineId() {
  return "poli_" + crypto.randomBytes(6).toString("base64url");
}

function hydrateLine(line) {
  const sku = typeof line?.sku === "string" ? line.sku.trim() : "";
  const qty = Number(line?.qty);
  const safeQty = Number.isFinite(qty) && qty > 0 ? Math.floor(qty) : 1;
  const unitCents = Number.isFinite(Number(line?.unitPriceCents)) ? Math.max(0, Math.floor(Number(line.unitPriceCents))) : 0;
  return {
    id: typeof line?.id === "string" && line.id ? line.id : makePoLineId(),
    sku,
    qty: safeQty,
    sourceListId: typeof line?.sourceListId === "string" ? line.sourceListId : null,
    sourceLineId: typeof line?.sourceLineId === "string" ? line.sourceLineId : null,
    unitPriceCents: unitCents,
    lineTotalCents: unitCents * safeQty,
    notes: typeof line?.notes === "string" ? line.notes.slice(0, 500) : ""
  };
}

function blankPo() {
  const created = nowIso();
  return {
    id: "",
    status: "draft",

    supplierId: null,
    // Snapshots of supplier fields at create time. The PDF + email use
    // these so a supplier rename doesn't retroactively change a sent PO.
    supplierName: "",
    supplierEmail: "",
    supplierContactName: "",
    supplierPhone: "",
    supplierAddress: "",

    // Source material-list ids. Usually one; supports many for the case
    // where the admin merges several lists into one PO.
    sourceMaterialListIds: [],

    lineItems: [],
    subtotalCents: 0,

    notes: "",                  // free-form notes; printed on the PDF
    internalNotes: "",          // never on the PDF — admin-only

    // Email send state. Snapshotted at send time so we can show "sent
    // to orders@vendor.com on Mar 14" without re-fetching the supplier.
    emailedToEmail: "",
    emailedToName: "",
    emailSubject: "",

    sentAt: null,
    receivedAt: null,
    cancelledAt: null,
    cancelReason: "",

    createdAt: created,
    updatedAt: created,
    createdBy: "admin",

    history: [
      { ts: created, action: "created", by: "admin", note: "" }
    ]
  };
}

function hydrate(rec) {
  const base = blankPo();
  return {
    ...base,
    ...rec,
    status: STATUSES.includes(rec?.status) ? rec.status : "draft",
    sourceMaterialListIds: Array.isArray(rec?.sourceMaterialListIds) ? rec.sourceMaterialListIds.slice() : [],
    lineItems: Array.isArray(rec?.lineItems) ? rec.lineItems.map(hydrateLine) : [],
    history: Array.isArray(rec?.history) ? rec.history.slice(-200) : []
  };
}

async function nextPoId(year) {
  const records = await readAll();
  const prefix = `PO-${year}-`;
  let max = 0;
  for (const r of records) {
    if (typeof r.id === "string" && r.id.startsWith(prefix)) {
      const n = parseInt(r.id.slice(prefix.length), 10);
      if (Number.isFinite(n) && n > max) max = n;
    }
  }
  return `${prefix}${String(max + 1).padStart(4, "0")}`;
}

function appendHistory(record, entry) {
  record.history = Array.isArray(record.history) ? record.history : [];
  record.history.push({ ts: nowIso(), by: "admin", note: "", ...entry });
  if (record.history.length > 200) record.history = record.history.slice(-200);
}

function recomputeSubtotal(record) {
  let sub = 0;
  for (const l of record.lineItems || []) sub += Number(l.lineTotalCents) || 0;
  record.subtotalCents = sub;
}

// ---- CRUD -----------------------------------------------------------

async function list({ status = null, supplierId = null, materialListId = null } = {}) {
  const records = await readAll();
  return records.filter((r) => {
    if (status && r.status !== status) return false;
    if (supplierId && r.supplierId !== supplierId) return false;
    if (materialListId && !(r.sourceMaterialListIds || []).includes(materialListId)) return false;
    return true;
  });
}

async function get(id) {
  const records = await readAll();
  return records.find((r) => r.id === id) || null;
}

async function create({
  supplierId = null,
  supplierName = "",
  supplierEmail = "",
  supplierContactName = "",
  supplierPhone = "",
  supplierAddress = "",
  sourceMaterialListIds = [],
  lineItems = [],
  notes = "",
  internalNotes = "",
  createdBy = "admin"
} = {}) {
  const records = await readAll();
  const year = new Date().getUTCFullYear();
  const id = await nextPoId(year);
  const rec = blankPo();
  rec.id = id;
  rec.supplierId = supplierId ? String(supplierId) : null;
  rec.supplierName = String(supplierName || "").trim().slice(0, 200);
  rec.supplierEmail = String(supplierEmail || "").trim().toLowerCase().slice(0, 254);
  rec.supplierContactName = String(supplierContactName || "").trim().slice(0, 120);
  rec.supplierPhone = String(supplierPhone || "").trim().slice(0, 40);
  rec.supplierAddress = String(supplierAddress || "").trim().slice(0, 400);
  rec.sourceMaterialListIds = Array.isArray(sourceMaterialListIds) ? sourceMaterialListIds.filter(Boolean).map(String) : [];
  rec.lineItems = Array.isArray(lineItems) ? lineItems.map(hydrateLine) : [];
  rec.notes = String(notes || "").slice(0, 4000);
  rec.internalNotes = String(internalNotes || "").slice(0, 4000);
  rec.createdBy = String(createdBy || "admin").slice(0, 80);
  recomputeSubtotal(rec);
  records.unshift(rec);
  await writeAll(records);
  return rec;
}

// Update editable fields. Status changes ALWAYS go through the dedicated
// markSent / markReceived / markCancelled functions so the source-line
// state flips happen atomically with the PO state.
async function update(id, patch = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const current = records[idx];
  if (current.status !== "draft" && (Array.isArray(patch.lineItems) || patch.supplierId !== undefined)) {
    throw new Error(`Cannot edit line items or supplier on a ${current.status} PO`);
  }
  const next = { ...current };
  const allowedTop = ["notes", "internalNotes", "supplierName", "supplierEmail", "supplierContactName", "supplierPhone", "supplierAddress"];
  for (const key of allowedTop) {
    if (Object.prototype.hasOwnProperty.call(patch, key)) {
      if (key === "supplierEmail") {
        next.supplierEmail = String(patch.supplierEmail || "").trim().toLowerCase().slice(0, 254);
      } else {
        next[key] = String(patch[key] == null ? "" : patch[key]).slice(0, 4000);
      }
    }
  }
  if (patch.supplierId !== undefined) {
    next.supplierId = patch.supplierId ? String(patch.supplierId) : null;
  }
  if (Array.isArray(patch.lineItems)) {
    next.lineItems = patch.lineItems.map(hydrateLine);
    recomputeSubtotal(next);
  }
  next.updatedAt = nowIso();
  records[idx] = next;
  await writeAll(records);
  return next;
}

// Mark a draft as sent. Records the email send-state snapshot. Caller
// (server.js) is responsible for: actually rendering the PDF, calling
// the email sender, and flipping the source material-list lines to
// "ordered" with poId backref.
async function markSent(id, { toEmail, toName, subject } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status !== "draft") {
    throw new Error(`Can only send a draft PO. This one is "${rec.status}".`);
  }
  if (!rec.lineItems.length) throw new Error("Can't send a PO with no line items.");
  rec.status = "sent";
  rec.sentAt = nowIso();
  rec.emailedToEmail = String(toEmail || rec.supplierEmail || "").trim().toLowerCase();
  rec.emailedToName = String(toName || rec.supplierContactName || rec.supplierName || "");
  rec.emailSubject = String(subject || `Purchase Order ${rec.id}`).slice(0, 200);
  rec.updatedAt = rec.sentAt;
  appendHistory(rec, { action: "sent", note: rec.emailedToEmail });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

async function markReceived(id, { note = "" } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status !== "sent") {
    throw new Error(`Can only receive a sent PO. This one is "${rec.status}".`);
  }
  rec.status = "received";
  rec.receivedAt = nowIso();
  rec.updatedAt = rec.receivedAt;
  appendHistory(rec, { action: "received", note });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

async function markCancelled(id, { reason = "" } = {}) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const rec = records[idx];
  if (rec.status === "received") {
    throw new Error("Can't cancel a received PO. Mark a return separately.");
  }
  if (rec.status === "cancelled") return rec; // idempotent
  rec.status = "cancelled";
  rec.cancelledAt = nowIso();
  rec.cancelReason = String(reason || "").slice(0, 500);
  rec.updatedAt = rec.cancelledAt;
  appendHistory(rec, { action: "cancelled", note: rec.cancelReason });
  records[idx] = rec;
  await writeAll(records);
  return rec;
}

async function remove(id) {
  const records = await readAll();
  const idx = records.findIndex((r) => r.id === id);
  if (idx === -1) return null;
  const [removed] = records.splice(idx, 1);
  await writeAll(records);
  return removed;
}

// ---- Generation from a material list -------------------------------
//
// Group a material list's "need" lines by their primary supplier (the
// first entry in part.supplierIds[]). Returns:
//   {
//     ok: bool,
//     drafts: [{ supplierId, lineItems, subtotalCents }],
//     missingSupplier: [sku],   // need-line SKUs with no supplier assignment
//     missingSupplierLines: [{ sku, qty, lineId }]
//   }
//
// Caller: if drafts is non-empty, persist each via create() and gather
// the resulting PO ids. Use the missingSupplier list to surface a
// blocker UI ("3 SKUs need supplier assignment before generating").
//
// Pricing: snapshotted from `parts[sku].priceCents` at generation time.
function planDraftsFromMaterialList(list, parts) {
  if (!list || !Array.isArray(list.lineItems)) {
    return { ok: false, drafts: [], missingSupplier: [], missingSupplierLines: [] };
  }
  const drafts = new Map();   // supplierId -> { supplierId, lineItems[] }
  const missingSupplier = new Set();
  const missingSupplierLines = [];
  for (const line of list.lineItems) {
    if (line.status !== "need") continue;
    const part = parts && parts[line.sku];
    const supplierIds = (part && Array.isArray(part.supplierIds)) ? part.supplierIds : [];
    if (!supplierIds.length) {
      missingSupplier.add(line.sku);
      missingSupplierLines.push({ sku: line.sku, qty: line.qty, lineId: line.id });
      continue;
    }
    const primary = supplierIds[0];
    if (!drafts.has(primary)) {
      drafts.set(primary, { supplierId: primary, lineItems: [], subtotalCents: 0 });
    }
    const draft = drafts.get(primary);
    const unitCents = part && Number.isFinite(Number(part.priceCents)) ? Math.max(0, Math.floor(Number(part.priceCents))) : 0;
    const qty = Math.max(1, Math.floor(Number(line.qty) || 1));
    draft.lineItems.push({
      sku: line.sku,
      qty,
      sourceListId: list.id,
      sourceLineId: line.id,
      unitPriceCents: unitCents,
      lineTotalCents: unitCents * qty,
      notes: line.notes || ""
    });
    draft.subtotalCents += unitCents * qty;
  }
  return {
    ok: drafts.size > 0 && missingSupplier.size === 0,
    drafts: Array.from(drafts.values()),
    missingSupplier: Array.from(missingSupplier),
    missingSupplierLines
  };
}

module.exports = {
  STATUSES,
  list,
  get,
  create,
  update,
  markSent,
  markReceived,
  markCancelled,
  remove,
  planDraftsFromMaterialList
};
